<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5pa55qGI');
$cfg_Cs[2]=array(0,1,1,'6LWE6K6v');
$cfg_Cs[3]=array(0,1,1,'5oub6IGY');
$cfg_Cs[4]=array(0,1,1,'5YWz5LqO');
$cfg_Cs[5]=array(1,1,1,'5YWs55So5biC5pS/6KGM5Lia5L+d55CG');
$cfg_Cs[6]=array(1,1,1,'5Yy755aX6KGM5Lia5L+d55CG');
$cfg_Cs[7]=array(1,1,1,'54mp5rWB6KGM5Lia5L+d55CG');
$cfg_Cs[8]=array(1,1,1,'55S15a2Q56eR5oqA6KGM5Lia5L+d55CG');
$cfg_Cs[9]=array(1,1,1,'56ef6LWB6KGM5Lia5L+d55CG');
$cfg_Cs[10]=array(1,1,1,'5ZWG6LS45pyN5Yqh6KGM5Lia5L+d55CG');
?>