<?php
$z[0]=Array("quanming","\r\n",1,156);
$z[0][4]['itemname']="交易对手/对方客户全名:";
$z[0][4]['autofield']="1";
$z[0][4]['type']="text";
$z[0][4]['isnull']="true";
$z[0][4]['default']="";
$z[0][4]['maxlength']="250";
$z[0][4]['page']="";
$z[1]=Array("dtime","\r\n",159,288);
$z[1][4]['itemname']="交易时间";
$z[1][4]['autofield']="1";
$z[1][4]['type']="text";
$z[1][4]['isnull']="true";
$z[1][4]['default']="";
$z[1][4]['maxlength']="250";
$z[1][4]['page']="";
$z[2]=Array("xiangmu","\r\n",291,438);
$z[2][4]['itemname']="交易产品/ 服务项目";
$z[2][4]['autofield']="1";
$z[2][4]['type']="text";
$z[2][4]['isnull']="true";
$z[2][4]['default']="";
$z[2][4]['maxlength']="250";
$z[2][4]['page']="";

?>