
<field:quanming itemname="交易对手/对方客户全名:" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:quanming>

<field:dtime itemname="交易时间" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dtime>

<field:xiangmu itemname="交易产品/ 服务项目" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:xiangmu>

<field:jine itemname="应收账款金额（万元）" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:jine>
