
<field:name itemname="单位名称：" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:name>



<field:lxr itemname="联系人（职务）：" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:lxr>

<field:dz itemname="经营地址：" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:dz>

<field:sj itemname="手机：" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:sj>
