<li>
                    	<div class="time">
                        	<b>[field:pubdate function=MyDate('d',@me)/] </b>[field:pubdate function=MyDate('Y-m',@me)/] 
                        </div>
                        <dl class="clearfix">
                        	<dt><a href="[field:arcurl/]" ><img src="[field:litpic/]"  alt=""/></a></dt>
                            <dd>
                            	<div class="title"><a href="[field:arcurl/]" >[field:title/]</a></div>
                                <div class="des">
                                	[field:description/]
                                </div>
                                <div class="date"><span>[field:pubdate function=MyDate('Y-m-d',@me)/] </span></div>
                                <a href="[field:arcurl/]"  class="more">+ 查看详情</a>
                            </dd>
                        </dl>
                    </li>