<?php
$z[0]=Array("pubdate","",75,116);
$z[0][4]['function']="MyDate('d',@me)";
$z[1]=Array("pubdate","",121,164);
$z[1][4]['function']="MyDate('Y-m',@me)";
$z[2]=Array("arcurl","",284,299);
$z[3]=Array("litpic","",312,327);
$z[4]=Array("arcurl","",440,455);
$z[5]=Array("title","",458,472);
$z[6]=Array("description","",568,588);
$z[7]=Array("pubdate","",686,731);
$z[7][4]['function']="MyDate('Y-m-d',@me)";
$z[8]=Array("arcurl","",788,803);

?>